###
POST {{base_url}}/api/create-event
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "title": "test",
  "description": "This is description",
  "max_capacity": "200"
}


###
GET {{base_url}}/api/get-event-tickets?id=61
Content-Type: application/json
Authorization: Bearer {{token}}


###
POST {{base_url}}/api/purchase-ticket
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "id": 31,
  "ticket_id": 4214
}